name: coast
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - mamba 
  - python
  - pip
  - cartopy
  - gsw
  - pip:
    - numpy
    - dask
    - xarray
    - matplotlib
    - netCDF4
    - scipy
    - gsw
    - utide
    - scikit-learn
    - scikit-image
    - statsmodels
    - pydap
    - lxml
    - requests
    - spyder
    - jupyterlab
